apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: hosted:v1.0  # Use your image name and tag
        ports:
        - containerPort: 8000  # The port your app listens on
        resources:
          requests:
            memory: "128Mi"  # Guaranteed memory for the container
            cpu: "250m"      # Guaranteed CPU for the container
          limits:
            memory: "256Mi"  # Maximum memory the container can use
            cpu: "500m"      # Maximum CPU the container can use
