apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Match this with the containerPort in the Deployment
  type: LoadBalancer  # Or use NodePort if using Minikube or Kind
